import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const source=ts.transpileModule(fs.readFileSync('functions/api/rfq.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {onRequestGet,onRequestPost}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
let count=0,saved=0;
const env={RFQ_HASH_SALT:'test-only-not-for-deployment-123456789',PUBLIC_CONTACT_EMAIL:'test@example.com',RFQ_RETENTION_DAYS:'30',RFQ_DB:{prepare(sql){return {bind(){return this},async run(){if(sql.startsWith('INSERT INTO inquiries'))saved++;},async first(){return {count:++count}}}}}};
const valid={type:'standard',name:'Test',contact:'test@example.com',details:'Test request only',consent:'on',website:'',started:Date.now()-5000};
const context=(data=valid,origin='https://ribloxen.com')=>({env,request:new Request('https://ribloxen.com/api/rfq',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1'},body:JSON.stringify(data)})});
assert.equal((await (await onRequestGet({env:{}})).json()).ready,false);
assert.equal((await onRequestPost({...context(),env:{}})).status,503);
assert.equal((await onRequestPost(context(valid,'https://other.example'))).status,403);
assert.equal((await onRequestPost(context({...valid,consent:''}))).status,400);
assert.equal((await onRequestPost(context({...valid,contact:'invalid'}))).status,400);
assert.equal((await onRequestPost(context({...valid,website:'spam'}))).status,400);
assert.equal((await onRequestPost(context({...valid,details:'x'.repeat(25000)}))).status,413);
assert.equal(saved,0);
for(let i=0;i<5;i++)assert.equal((await onRequestPost(context())).status,201);
assert.equal((await onRequestPost(context())).status,429);
assert.equal(saved,5);
const broken={...env,RFQ_DB:{prepare(){throw new Error('database unavailable')}}};
assert.equal((await onRequestPost({...context(),env:broken})).status,503);
console.log('PASS: disabled, origin, consent, validation, honeypot, body limit, success, rate limit, database failure');
